name: at_app
description: A command line tool to help developers build an @ platform application.
version: 0.1.2+2
repository: https://github.com/atsign-foundation/at_app
homepage: https://atsign.dev/

executables:
  at_app:

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  at_client_mobile: ^2.0.3
  at_onboarding_flutter: ^2.1.2
  at_utils: ^2.0.4
  dotenv: ^3.0.0
  flutter:
    sdk: flutter
  flutter_tools:
    sdk: flutter
  path_provider: ^2.0.2
  version: ^2.0.0

dev_dependencies:
  pedantic: ^1.10.0
