name: build_job
description: Build at_app repo - make sure to run setup_repo first

runs:
  using: composite

  steps:
    - name: Build at_app_bundler
      shell: bash
      run: |
        chmod +x ./tools/build_at_app_create.sh
        ./tools/build_at_app_create.sh --no-analyze

    - name: Build at_app_create
      shell: bash
      run: |
        chmod +x ./tools/build_at_app_create.sh
        ./tools/build_at_app_create.sh --no-analyze

    - name: Bundle templates into at_app
      shell: bash
      run: |
        chmod +x ./tools/bundle_templates.sh
        ./tools/bundle_templates.sh --no-analyze

    - name: Build at_app
      shell: bash
      run: |
        chmod +x ./tools/build_at_app.sh
        ./tools/build_at_app.sh --no-analyze
