name: install_dependencies_job
description: Install dependencies for at_app repo

runs:
  using: composite
  steps:
    - name: Install melos
      run: dart pub global activate melos
      shell: bash

    - name: Bootstrap project with melos
      run: dart pub global run melos bootstrap
      shell: bash

    - id: path_source
      uses: mikefarah/yq@v4.27.5
      with:
        cmd: yq '.packages.at_app_create.source == "path"' packages/at_app/pubspec.lock

    - name: Verify melos bootstrap local linkage
      run: echo ${{ steps.path_source.outputs.result }}
      shell: bash

    - name: Install mason_cli
      run: dart pub global activate mason_cli
      shell: bash
