name: at_app_templates
repository: https://github.com/atsign-foundation/at_app

packages:
  - demos/*/*
  - samples/*/*
  - templates/*/*

scripts:
  upgrade: melos exec -- dart pub upgrade
  upgrade:major: melos exec -- dart pub upgrade --major-versions
  get: melos exec -- dart pub get
